config/routes.rb
Rails.application.routes.draw do
  get 'category/new'

  get 'category/create'

  get 'category/update'

  get 'category/edit'

  get 'category/destroy'

  get 'category/show'

  get 'category/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :categories
  resources :faqs

  root 'faqs#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	
	has_many :faqs

end

app/models/faq.rb
class Faq < ActiveRecord::Base

	belongs_to :category
	include PgSearch
	pg_search_scope :faq_search, :against => :title


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def index
    @category = Category.all
  end

  
  def show
  end


  def new
    @category = Category.new
  end

  def edit
  end


  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'category was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'category was successfully destroyed.'
  end

  private
   
    def set_category
      @category = Category.find(params[:id])
    end


    def category_params
      params.require(:category).permit(:name, :faq_id)
    end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  def index
    @faqs = if !params[:query].blank?
      Faq.faq_search(params[:query])
    else
      Faq.all
    end
    @general_faqs = Faq.where(:category_id => 1)
    @admin_faqs = Faq.where(:category_id => 2)
  end

  # GET /faqs/1
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      redirect_to @faq, notice: 'Faq was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /faqs/1
  def update
    if @faq.update(faq_params)
      redirect_to @faq, notice: 'Faq was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /faqs/1
  def destroy
    @faq.destroy
    redirect_to faqs_url, notice: 'Faq was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def faq_params
      params.require(:faq).permit(:title, :body, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/category/create.html.erb
<h1>Category#create</h1>
<p>Find me in app/views/category/create.html.erb</p>

app/views/category/destroy.html.erb
<h1>Category#destroy</h1>
<p>Find me in app/views/category/destroy.html.erb</p>

app/views/category/edit.html.erb
<h1>Category#edit</h1>
<p>Find me in app/views/category/edit.html.erb</p>

app/views/category/index.html.erb
<h1>Category#index</h1>
<p>Find me in app/views/category/index.html.erb</p>

app/views/category/new.html.erb
<h1>Category#new</h1>
<p>Find me in app/views/category/new.html.erb</p>

app/views/category/show.html.erb
<h1>Category#show</h1>
<p>Find me in app/views/category/show.html.erb</p>

app/views/category/update.html.erb
<h1>Category#update</h1>
<p>Find me in app/views/category/update.html.erb</p>

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<br>
<h1 class="center red big">FAQ</h1>
<br>
<a><p id="searchLink">search</p></a>


<div id="center_search">
<%= form_tag faqs_path, method: :get do %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
<% end %>
</div>

<br>
<br>
<br>
<br>
<br>

<div class="row">
  <div class="col-md-6">
    <br>
    <h4 class ="center">GENERAL</h4>
    <br>
    <% @general_faqs.each do |faq| %>
    <div class="well">
        <h4><em><strong><%= link_to "#{faq.title}", faq %></strong></em></h4>
        <br>
    <!--     <%= raw faq.body %> -->
        <br>
      </div>
    <% end %>
    </div>

  <div class="col-md-6">
    <br>
    <h4 class ="center">ADMIN</h4>
    <br>
    <% @admin_faqs.each do |faq| %>
    <div class="well">
        <h4><em><strong><%= link_to "#{faq.title}", faq %></strong></em></h4>
        <br>
    <!--     <%= raw faq.body %> -->
        <br>
      </div>
    <% end %>
  </div>
</div>



<button id="click" class="center">Go up!</button>
<br>
<br>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
<p>
  <strong>Title:</strong>
  <%= @faq.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= raw @faq.body %>
</p>

<br>
</div>
<%= link_to 'Back', faqs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Switchboard FAQs</title>
  <link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/simplex/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <link href='assets/stylesheets/styles.css.scss' rel="stylesheet"> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = 'container'>
		<div class="row">
  			<div class="col-md-10 col-md-offset-1">
			<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>